### ISSUE TITLE
Consistency of filenames/directory structure

### ISSUE THREAD

**Issue by DACrowder** [stephendoyle1992/395_Project_2018#38]
Are we doing .gohtml or .tmpl for template files?
Are we using the /templates/ or /views/ folder for templates? (I think we should move /templates + /public into /views/ so we can have /views/index.html as our single-page which pulls templates from /views/templates/, and js/css from /views/public,  but I digress).

PS. I say that so we can stick with a single route - /views/ - to pull the public content (js/css)
PPS. Great work on the templating and stuff Rina!

**Comment by csrina** [comment]
can we go over this today? from what I have seen you have a bunch of templates and call the "content" template for the required page which points to the other templates (ie header or footer or whatever else) and builds the page.

Right now instead of calling an HTML page a call to an endpoint (ie /login not /login/login.html) will pull the desired page. I was under the assumption that with this we no longer need a single-page to pull templates from but we build the pages with whichever templates we want.

As for the location of the files, there is a bunch of stuff under views that I was too sure about so I stirred clear if you can give me a quick tour that would be helpful.

**Comment by DACrowder** [comment]
Yeah we should talk about this as group today/after demo tomorrow.

I'm more comfortable with your proposed approach over going single-page, to be honest, so that sounds good to me.


I can give a rundown on how I envisioned views working, and we can decide as a group if we want to go that route, or keep separate directories from root.

**Comment by csrina** [comment]
As discussed will move templates and public under views, other static html pages will be converted to templates as we go along.
